# Generated by Django 3.0.6 on 2020-07-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='Comments',
        ),
    ]
