# Generated by Django 3.0.6 on 2020-07-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200713_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhtor',
            new_name='author',
        ),
    ]
