# Generated by Django 3.0.6 on 2020-08-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20200831_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
